/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_v1_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_api_v1_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Article Annotations */
        get: operations["article_annotations_api_v1_articles__article_id__annotations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}/nlp/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Article */
        post: operations["reprocess_article_api_v1_articles__article_id__nlp_reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{article_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Article Request */
        post: operations["process_article_request_api_v1_articles__article_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clustering/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clustering Failures */
        get: operations["clustering_failures_api_v1_clustering_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clustering/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Clustering Job */
        post: operations["retry_clustering_job_api_v1_clustering_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clustering/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clustering Status */
        get: operations["clustering_status_api_v1_clustering_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cluster */
        get: operations["get_cluster_api_v1_clusters__cluster_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feeds */
        get: operations["list_feeds_api_v1_feeds_get"];
        put?: never;
        /** Create Feed */
        post: operations["create_feed_api_v1_feeds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{feed_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed */
        get: operations["get_feed_api_v1_feeds__feed_id__get"];
        put?: never;
        post?: never;
        /** Retire Feed */
        delete: operations["retire_feed_api_v1_feeds__feed_id__delete"];
        options?: never;
        head?: never;
        /** Update Feed */
        patch: operations["update_feed_api_v1_feeds__feed_id__patch"];
        trace?: never;
    };
    "/api/v1/feeds/{feed_id}/fetches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fetches */
        get: operations["list_fetches_api_v1_feeds__feed_id__fetches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feeds/{feed_id}/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll Feed */
        post: operations["poll_feed_api_v1_feeds__feed_id__poll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backlog */
        get: operations["backlog_api_v1_jobs_backlog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlp/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Lookup */
        get: operations["entity_lookup_api_v1_nlp_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlp/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nlp Failures */
        get: operations["nlp_failures_api_v1_nlp_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlp/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Nlp Job */
        post: operations["retry_nlp_job_api_v1_nlp_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlp/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Keyword Lookup */
        get: operations["keyword_lookup_api_v1_nlp_keywords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlp/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nlp Status */
        get: operations["nlp_status_api_v1_nlp_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nlp/stop-words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stop Words */
        get: operations["get_stop_words_api_v1_nlp_stop_words_get"];
        /** Put Stop Words */
        put: operations["put_stop_words_api_v1_nlp_stop_words_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Searches */
        get: operations["list_searches_api_v1_saved_searches_get"];
        put?: never;
        /** Create Search */
        post: operations["create_search_api_v1_saved_searches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-searches/{saved_search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Search */
        get: operations["get_search_api_v1_saved_searches__saved_search_id__get"];
        put?: never;
        post?: never;
        /** Delete Search */
        delete: operations["delete_search_api_v1_saved_searches__saved_search_id__delete"];
        options?: never;
        head?: never;
        /** Update Search */
        patch: operations["update_search_api_v1_saved_searches__saved_search_id__patch"];
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Articles */
        get: operations["search_articles_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/indexing/articles/{article_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Indexing */
        post: operations["retry_indexing_api_v1_search_indexing_articles__article_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/indexing/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexing Failures */
        get: operations["indexing_failures_api_v1_search_indexing_failures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/indexing/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indexing Status */
        get: operations["indexing_status_api_v1_search_indexing_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Sources */
        get: operations["search_sources_api_v1_search_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Timeline */
        get: operations["search_timeline_api_v1_search_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnotationLookupItem */
        AnnotationLookupItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Normalized Text */
            normalized_text: string;
            /** Text */
            text: string;
        };
        /** AnnotationLookupPage */
        AnnotationLookupPage: {
            /** Items */
            items: components["schemas"]["AnnotationLookupItem"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ArticleAnnotationsResponse */
        ArticleAnnotationsResponse: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityResponse"][];
            /** Countries */
            countries: components["schemas"]["CountryAnnotationResponse"][];
            /** Entities */
            entities: components["schemas"]["EntityAnnotationResponse"][];
            /** Keywords */
            keywords: components["schemas"]["KeywordAnnotationResponse"][];
            language: components["schemas"]["LanguageAnnotationResponse"] | null;
            /** Processors */
            processors: components["schemas"]["ProcessorOutcomeResponse"][];
            /** Source Countries */
            source_countries: string[];
        };
        /** ArticleContentResponse */
        ArticleContentResponse: {
            /** Change Count */
            change_count: number;
            /** Content Hash */
            content_hash: string;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at: string;
            /** Extractor Name */
            extractor_name: string;
            /** Extractor Version */
            extractor_version: string;
            /** Html Retained */
            html_retained: boolean;
            /**
             * Last Content Change At
             * Format: date-time
             */
            last_content_change_at: string;
            /** Previous Content Hash */
            previous_content_hash: string | null;
            /** Text */
            text: string;
        };
        /** ArticleDetailResponse */
        ArticleDetailResponse: {
            /** Clustering Status */
            clustering_status?: string | null;
            content: components["schemas"]["ArticleContentResponse"] | null;
            /**
             * First Discovered At
             * Format: date-time
             */
            first_discovered_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Url */
            normalized_url: string;
            /** Original Url */
            original_url: string;
            /** Processing */
            processing: components["schemas"]["ArticleJobSummary"][];
            /** Provenance */
            provenance: components["schemas"]["ArticleProvenance"][];
            /** Published At */
            published_at: string | null;
            /** Related */
            related?: components["schemas"]["RelatedArticle"][];
            story_cluster?: components["schemas"]["ArticleStoryCluster"] | null;
            /** Title */
            title: string;
        };
        /** ArticleJobSummary */
        ArticleJobSummary: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Category */
            error_category: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Requested Mode */
            requested_mode: string;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
        };
        /** ArticlePage */
        ArticlePage: {
            /** Items */
            items: components["schemas"]["ArticleResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ArticleProvenance */
        ArticleProvenance: {
            /** Description */
            description: string | null;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
            /**
             * Feed Id
             * Format: uuid
             */
            feed_id: string;
            /** Feed Name */
            feed_name: string;
            /** Guid */
            guid: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ArticleResponse */
        ArticleResponse: {
            /**
             * First Discovered At
             * Format: date-time
             */
            first_discovered_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Url */
            normalized_url: string;
            /** Original Url */
            original_url: string;
            /** Provenance */
            provenance: components["schemas"]["ArticleProvenance"][];
            /** Published At */
            published_at: string | null;
            /** Title */
            title: string;
        };
        /** ArticleStoryCluster */
        ArticleStoryCluster: {
            /** Article Count */
            article_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Count */
            source_count: number;
        };
        /** AttemptResponse */
        AttemptResponse: {
            /** Attempt Number */
            attempt_number: number;
            /** Completed At */
            completed_at: string | null;
            /** Error Category */
            error_category: string | null;
            /** Error Message */
            error_message: string | null;
            /** Http Status */
            http_status: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Stage */
            stage: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** BacklogResponse */
        BacklogResponse: {
            /** Failed */
            failed: number;
            /** Queued */
            queued: number;
            /** Retrying */
            retrying: number;
            /** Running */
            running: number;
        };
        /** CapabilityResponse */
        CapabilityResponse: {
            /** Detail */
            detail?: string | null;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Version */
            version?: string | null;
        };
        /** ClusterMemberFeedRef */
        ClusterMemberFeedRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ClusterMemberPage */
        ClusterMemberPage: {
            /** Items */
            items: components["schemas"]["ClusterMemberResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ClusterMemberResponse */
        ClusterMemberResponse: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /**
             * Effective Date
             * Format: date-time
             */
            effective_date: string;
            /** Feeds */
            feeds: components["schemas"]["ClusterMemberFeedRef"][];
            /** Score */
            score: number;
            /** Title */
            title: string;
        };
        /** ClusteringFailurePage */
        ClusteringFailurePage: {
            /** Items */
            items: components["schemas"]["ClusteringFailureResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ClusteringFailureResponse */
        ClusteringFailureResponse: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Attempt Count */
            attempt_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Category */
            error_category: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ClusteringMutationResponse */
        ClusteringMutationResponse: {
            /** Jobs Created */
            jobs_created: number;
            /** Status */
            status: string;
        };
        /** ClusteringStatusResponse */
        ClusteringStatusResponse: {
            /** Algorithm Version */
            algorithm_version: string;
            /**
             * Clustered Articles
             * @default 0
             */
            clustered_articles: number;
            /**
             * Clusters
             * @default 0
             */
            clusters: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Retrying
             * @default 0
             */
            retrying: number;
            /**
             * Running
             * @default 0
             */
            running: number;
        };
        /** CountryAnnotationResponse */
        CountryAnnotationResponse: {
            /** Country Code */
            country_code: string;
            /** Fresh */
            fresh: boolean;
            /** Inferred */
            inferred: boolean;
            /** Occurrence Count */
            occurrence_count: number;
            /** Occurrences */
            occurrences: components["schemas"]["OccurrenceResponse"][];
            /** Role */
            role: string;
            /** Rule Version */
            rule_version: string;
        };
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** CursorPage */
        CursorPage: {
            /** Items */
            items: components["schemas"]["FeedResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** EntityAnnotationResponse */
        EntityAnnotationResponse: {
            /** Entity Type */
            entity_type: string;
            /** Fresh */
            fresh: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Normalized Text */
            normalized_text: string;
            /** Occurrence Count */
            occurrence_count: number;
            /** Occurrences */
            occurrences: components["schemas"]["OccurrenceResponse"][];
            /** Original Label */
            original_label: string | null;
            /** Relevance */
            relevance: number;
            /** Text */
            text: string;
        };
        /** FeedCreate */
        FeedCreate: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Expected Language */
            expected_language?: string | null;
            /**
             * Fetching Mode
             * @default rss
             * @enum {string}
             */
            fetching_mode: "rss" | "full_text" | "full_text_html";
            /** Name */
            name: string;
            /**
             * Poll Interval Minutes
             * @default 30
             */
            poll_interval_minutes: number;
            /** Source Country */
            source_country?: string | null;
            /** Tags */
            tags?: string[];
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** FeedResponse */
        FeedResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Expected Language */
            expected_language: string | null;
            /** Fetching Mode */
            fetching_mode: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Success At */
            last_success_at: string | null;
            /** Name */
            name: string;
            /**
             * Next Poll At
             * Format: date-time
             */
            next_poll_at: string;
            /** Poll Interval Minutes */
            poll_interval_minutes: number;
            /** Source Country */
            source_country: string | null;
            /** Tags */
            tags: string[];
            /** Url */
            url: string;
        };
        /** FeedUpdate */
        FeedUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Expected Language */
            expected_language?: string | null;
            /** Fetching Mode */
            fetching_mode?: ("rss" | "full_text" | "full_text_html") | null;
            /** Name */
            name?: string | null;
            /** Poll Interval Minutes */
            poll_interval_minutes?: number | null;
            /** Source Country */
            source_country?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Url */
            url?: string | null;
        };
        /** FetchPage */
        FetchPage: {
            /** Items */
            items: components["schemas"]["FetchResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FetchResponse */
        FetchResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Completed At */
            completed_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Entry Count */
            entry_count: number;
            /** Error Category */
            error_category: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Feed Id
             * Format: uuid
             */
            feed_id: string;
            /** Http Status */
            http_status: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Invalid Entry Count */
            invalid_entry_count: number;
            /** New Article Count */
            new_article_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HighlightSegment */
        HighlightSegment: {
            /**
             * Marked
             * @default false
             */
            marked: boolean;
            /** Text */
            text: string;
        };
        /** IndexFailure */
        IndexFailure: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Attempt Count */
            attempt_count: number;
            /** Error Category */
            error_category: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index Name */
            index_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** IndexFailurePage */
        IndexFailurePage: {
            /** Items */
            items: components["schemas"]["IndexFailure"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** IndexStatus */
        IndexStatus: {
            /** Active Rebuild */
            active_rebuild?: {
                [key: string]: unknown;
            } | null;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Retrying
             * @default 0
             */
            retrying: number;
            /**
             * Running
             * @default 0
             */
            running: number;
        };
        /**
         * InvestigationState
         * @description Complete search investigation, using the /search query parameter names.
         */
        InvestigationState: {
            /** After */
            after?: string | null;
            /** Before */
            before?: string | null;
            /** Content Available */
            content_available?: boolean | null;
            /** Entity Id */
            entity_id?: string[];
            /** Entity Type */
            entity_type?: string[];
            /**
             * Interval
             * @default auto
             * @enum {string}
             */
            interval: "auto" | "hour" | "day" | "week" | "month" | "year";
            /** Keyword Id */
            keyword_id?: string[];
            /** Language */
            language?: string[];
            /** Mentioned Country */
            mentioned_country?: string[];
            /** Processing Status */
            processing_status?: string[];
            /**
             * Q
             * @default
             */
            q: string;
            /**
             * Sort
             * @default relevance
             * @enum {string}
             */
            sort: "relevance" | "newest" | "oldest" | "most_sources";
            /** Source Country */
            source_country?: string[];
            /** Source Id */
            source_id?: string[];
            /** Story Cluster Id */
            story_cluster_id?: string[];
            /** Story Country */
            story_country?: string[];
        };
        /** JobPage */
        JobPage: {
            /** Items */
            items: components["schemas"]["JobResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Article Title */
            article_title: string;
            /** Attempts */
            attempts?: components["schemas"]["AttemptResponse"][];
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Category */
            error_category: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Requested Mode */
            requested_mode: string;
            /** Stage */
            stage: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /** KeywordAnnotationResponse */
        KeywordAnnotationResponse: {
            /** Fresh */
            fresh: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Normalized Text */
            normalized_text: string;
            /** Occurrence Count */
            occurrence_count: number;
            /** Occurrences */
            occurrences: components["schemas"]["OccurrenceResponse"][];
            /** Raw Score */
            raw_score: number;
            /** Relevance */
            relevance: number;
            /** Text */
            text: string;
        };
        /** LanguageAnnotationResponse */
        LanguageAnnotationResponse: {
            /** Confidence */
            confidence: number;
            /** Fresh */
            fresh: boolean;
            /** Language */
            language: string;
            /** Margin */
            margin: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** NlpFailurePage */
        NlpFailurePage: {
            /** Items */
            items: components["schemas"]["NlpFailureResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** NlpFailureResponse */
        NlpFailureResponse: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Attempt Count */
            attempt_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Category */
            error_category: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Processor */
            processor: string;
        };
        /** NlpMutationResponse */
        NlpMutationResponse: {
            /** Jobs Created */
            jobs_created: number;
            /** Status */
            status: string;
        };
        /** NlpStatusResponse */
        NlpStatusResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityResponse"][];
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /** Reprocessing */
            reprocessing: {
                [key: string]: unknown;
            }[];
            /**
             * Retrying
             * @default 0
             */
            retrying: number;
            /**
             * Running
             * @default 0
             */
            running: number;
        };
        /** OccurrenceResponse */
        OccurrenceResponse: {
            /** End */
            end: number;
            /** Input End */
            input_end: number;
            /** Input Start */
            input_start: number;
            /** Reference Id */
            reference_id: string | null;
            /** Section */
            section: string;
            /** Start */
            start: number;
        };
        /** PollResponse */
        PollResponse: {
            /**
             * Fetch Id
             * Format: uuid
             */
            fetch_id: string;
            /** Reused */
            reused: boolean;
            /** Status */
            status: string;
        };
        /** ProcessRequest */
        ProcessRequest: {
            /**
             * Mode
             * @default full_text
             * @enum {string}
             */
            mode: "full_text" | "full_text_html";
        };
        /** ProcessResponse */
        ProcessResponse: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Reused */
            reused: boolean;
            /** Status */
            status: string;
        };
        /** ProcessorOutcomeResponse */
        ProcessorOutcomeResponse: {
            /** Algorithm Version */
            algorithm_version?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Completed Generation */
            completed_generation: number;
            /** Configuration Fingerprint */
            configuration_fingerprint: string;
            /** Detail */
            detail?: string | null;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Model Version */
            model_version?: string | null;
            /** Processor */
            processor: string;
            /** Processor Version */
            processor_version: string;
            /** Requested Generation */
            requested_generation: number;
            /** Status */
            status: string;
        };
        /** RelatedArticle */
        RelatedArticle: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /**
             * Effective Date
             * Format: date-time
             */
            effective_date: string;
            /** Score */
            score: number;
            /** Title */
            title: string;
        };
        /** ReprocessRequest */
        ReprocessRequest: {
            /** Processors */
            processors?: string[];
        };
        /** RetryIndexResponse */
        RetryIndexResponse: {
            /** Status */
            status: string;
        };
        /** SavedSearchCreate */
        SavedSearchCreate: {
            /** Name */
            name: string;
            state: components["schemas"]["InvestigationState"];
        };
        /** SavedSearchPage */
        SavedSearchPage: {
            /** Items */
            items: components["schemas"]["SavedSearchResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SavedSearchResponse */
        SavedSearchResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Problem */
            problem: string | null;
            state: components["schemas"]["InvestigationState"] | null;
            /** State Version */
            state_version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SavedSearchUpdate */
        SavedSearchUpdate: {
            /** Name */
            name?: string | null;
            state?: components["schemas"]["InvestigationState"] | null;
        };
        /** SearchPage */
        SearchPage: {
            /** Items */
            items: components["schemas"]["SearchResult"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Distinct Source Count */
            distinct_source_count: number;
            /**
             * Effective Date
             * Format: date-time
             */
            effective_date: string;
            /** Highlights */
            highlights: components["schemas"]["HighlightSegment"][];
            /** Source Refs */
            source_refs: components["schemas"]["SearchResultSource"][];
            /** Sources */
            sources: string[];
            story_cluster?: components["schemas"]["StoryClusterRef"] | null;
            /** Story Country */
            story_country?: string | null;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** SearchResultSource */
        SearchResultSource: {
            /** Country */
            country: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** SearchSource */
        SearchSource: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Retired */
            retired: boolean;
            /** Source Country */
            source_country: string | null;
        };
        /** SearchSourcePage */
        SearchSourcePage: {
            /** Items */
            items: components["schemas"]["SearchSource"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SearchTimeline */
        SearchTimeline: {
            /** Buckets */
            buckets: components["schemas"]["TimelineBucket"][];
            /**
             * Interval
             * @enum {string}
             */
            interval: "hour" | "day" | "week" | "month" | "year";
            /** Total */
            total: number;
        };
        /** StopWordsResponse */
        StopWordsResponse: {
            /** Configuration Fingerprint */
            configuration_fingerprint: string;
            /** Language */
            language: string;
            /** Revision */
            revision: number;
            /** Words */
            words: string[];
        };
        /** StopWordsUpdate */
        StopWordsUpdate: {
            /** Current Revision */
            current_revision: number;
            /** Words */
            words: string[];
        };
        /** StoryClusterDetailResponse */
        StoryClusterDetailResponse: {
            /** Algorithm Version */
            algorithm_version: string;
            /** Article Count */
            article_count: number;
            /** First Published At */
            first_published_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Published At */
            last_published_at: string | null;
            members: components["schemas"]["ClusterMemberPage"];
            /** Representative Article Id */
            representative_article_id: string | null;
            /** Source Count */
            source_count: number;
        };
        /** StoryClusterRef */
        StoryClusterRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Count */
            source_count: number;
        };
        /** TimelineBucket */
        TimelineBucket: {
            /** Count */
            count: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_articles_api_v1_articles_get: {
        parameters: {
            query?: {
                feed_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticlePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_api_v1_articles__article_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    article_annotations_api_v1_articles__article_id__annotations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleAnnotationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_article_api_v1_articles__article_id__nlp_reprocess_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprocessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NlpMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_article_request_api_v1_articles__article_id__process_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    csrf_api_v1_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    clustering_failures_api_v1_clustering_failures_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusteringFailurePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_clustering_job_api_v1_clustering_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusteringMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clustering_status_api_v1_clustering_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusteringStatusResponse"];
                };
            };
        };
    };
    get_cluster_api_v1_clusters__cluster_id__get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryClusterDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feeds_api_v1_feeds_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feed_api_v1_feeds_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_api_v1_feeds__feed_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_feed_api_v1_feeds__feed_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feed_api_v1_feeds__feed_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fetches_api_v1_feeds__feed_id__fetches_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poll_feed_api_v1_feeds__feed_id__poll_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                feed_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                article_id?: string | null;
                stage?: string | null;
                status?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backlog_api_v1_jobs_backlog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacklogResponse"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_lookup_api_v1_nlp_entities_get: {
        parameters: {
            query?: {
                q?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotationLookupPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nlp_failures_api_v1_nlp_failures_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NlpFailurePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_nlp_job_api_v1_nlp_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NlpMutationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keyword_lookup_api_v1_nlp_keywords_get: {
        parameters: {
            query?: {
                q?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotationLookupPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nlp_status_api_v1_nlp_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NlpStatusResponse"];
                };
            };
        };
    };
    get_stop_words_api_v1_nlp_stop_words_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopWordsResponse"];
                };
            };
        };
    };
    put_stop_words_api_v1_nlp_stop_words_put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StopWordsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopWordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_searches_api_v1_saved_searches_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_search_api_v1_saved_searches_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_api_v1_saved_searches__saved_search_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                saved_search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_search_api_v1_saved_searches__saved_search_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                saved_search_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_search_api_v1_saved_searches__saved_search_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                saved_search_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedSearchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_articles_api_v1_search_get: {
        parameters: {
            query?: {
                sort?: "relevance" | "newest" | "oldest" | "most_sources";
                limit?: number;
                cursor?: string | null;
                q?: string;
                source_id?: string[] | null;
                source_country?: string[] | null;
                after?: string | null;
                before?: string | null;
                content_available?: boolean | null;
                processing_status?: string[] | null;
                language?: string[] | null;
                entity_id?: string[] | null;
                entity_type?: string[] | null;
                keyword_id?: string[] | null;
                story_country?: string[] | null;
                mentioned_country?: string[] | null;
                story_cluster_id?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_indexing_api_v1_search_indexing_articles__article_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryIndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexing_failures_api_v1_search_indexing_failures_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexFailurePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexing_status_api_v1_search_indexing_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatus"];
                };
            };
        };
    };
    search_sources_api_v1_search_sources_get: {
        parameters: {
            query?: {
                q?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchSourcePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_timeline_api_v1_search_timeline_get: {
        parameters: {
            query?: {
                interval?: "auto" | "hour" | "day" | "week" | "month" | "year";
                q?: string;
                source_id?: string[] | null;
                source_country?: string[] | null;
                after?: string | null;
                before?: string | null;
                content_available?: boolean | null;
                processing_status?: string[] | null;
                language?: string[] | null;
                entity_id?: string[] | null;
                entity_type?: string[] | null;
                keyword_id?: string[] | null;
                story_country?: string[] | null;
                mentioned_country?: string[] | null;
                story_cluster_id?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchTimeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
