<script setup lang="ts">
import { computed, watch } from 'vue'
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../api'
const route = useRoute(), router = useRouter()
const client = useQueryClient()
const feedId = computed(() => typeof route.query.feed === 'string' ? route.query.feed : undefined)
const selectedId = computed(() => typeof route.query.article === 'string' ? route.query.article : undefined)
const feeds = useInfiniteQuery({ queryKey: ['feeds'], initialPageParam: undefined as string | undefined, queryFn: ({ pageParam }) => api.feeds(pageParam), getNextPageParam: page => page.next_cursor ?? undefined })
const articles = useInfiniteQuery({ queryKey: ['articles', feedId], initialPageParam: undefined as string | undefined, queryFn: ({ pageParam }) => api.articles(feedId.value, pageParam), getNextPageParam: page => page.next_cursor ?? undefined })
const feedItems = computed(() => feeds.data.value?.pages.flatMap(page => page.items) ?? [])
const articleItems = computed(() => articles.data.value?.pages.flatMap(page => page.items) ?? [])
const detail = useQuery({ queryKey: ['article', selectedId], queryFn: () => api.article(selectedId.value!), enabled: () => Boolean(selectedId.value), refetchInterval: 5000 })
const process = useMutation({ mutationFn: (mode: 'full_text' | 'full_text_html') => api.processArticle(selectedId.value!, mode), onSuccess: () => { client.invalidateQueries({ queryKey: ['article', selectedId] }); client.invalidateQueries({ queryKey: ['jobs'] }) } })
watch(selectedId, () => process.reset())
function setQuery(values: Record<string, string | undefined>) { router.replace({ query: { ...route.query, ...values } }) }
</script>
<template><header><div><p class="eyebrow">RSS archive</p><h2>Articles</h2></div><div><label class="filter">Source<select :value="feedId" @change="setQuery({ feed: ($event.target as HTMLSelectElement).value || undefined, article: undefined })"><option value="">All sources</option><option v-for="feed in feedItems" :key="feed.id" :value="feed.id">{{ feed.name }}</option></select></label><button v-if="feeds.hasNextPage.value" class="secondary" :disabled="feeds.isFetchingNextPage.value" @click="feeds.fetchNextPage()">Load more sources</button></div></header>
  <div class="article-layout"><section class="article-list panel"><p v-if="articles.isPending.value" class="muted">Loading articles…</p><p v-else-if="articles.isError.value" class="error">Could not load articles.</p><p v-else-if="!articleItems.length" class="muted">No collected articles.</p><button v-for="article in articleItems" :key="article.id" class="article-row" @click="setQuery({ article: article.id })"><strong>{{ article.title }}</strong><span>{{ new Date(article.first_discovered_at).toLocaleString() }}</span><small>{{ article.provenance.map(p => p.feed_name).join(', ') }}</small></button><button v-if="articles.hasNextPage.value" class="secondary" :disabled="articles.isFetchingNextPage.value" @click="articles.fetchNextPage()">Load more articles</button></section>
  <section class="panel detail"><p v-if="!selectedId" class="muted">Select an article to inspect its content and feed record.</p><p v-else-if="detail.isPending.value" class="muted">Loading article…</p><p v-else-if="detail.isError.value" class="error">Could not load article details.</p><template v-else-if="detail.data.value"><p class="eyebrow">Article detail</p><h3>{{ detail.data.value.title }}</h3><a :href="detail.data.value.original_url" target="_blank" rel="noopener noreferrer">Open original article</a><div class="actions processing-actions"><button :disabled="process.isPending.value" @click="process.mutate('full_text')">{{ detail.data.value.content ? 'Refresh text' : 'Fetch text' }}</button><button class="secondary" :disabled="process.isPending.value" @click="process.mutate('full_text_html')">Fetch and retain HTML</button></div><p v-if="process.isPending.value" class="muted">Scheduling processing…</p><p v-if="process.isSuccess.value" class="success">Processing scheduled.</p><p v-if="process.error.value" class="error">Could not schedule processing.</p><article v-if="detail.data.value.content" class="readable"><p class="eyebrow">Readable text</p><p class="muted">Extracted {{ new Date(detail.data.value.content.extracted_at).toLocaleString() }} · {{ detail.data.value.content.change_count }} changes · HTML {{ detail.data.value.content.html_retained ? 'retained' : 'temporary' }}</p><div class="article-text">{{ detail.data.value.content.text }}</div></article><section v-else class="processing"><strong>Content status</strong><p class="muted">{{ detail.data.value.processing[0]?.status || 'Not processed' }}</p><p v-if="detail.data.value.processing[0]?.error_message" class="error">{{ detail.data.value.processing[0].error_category }}: {{ detail.data.value.processing[0].error_message }}</p></section><dl><dt>Published</dt><dd>{{ detail.data.value.published_at ? new Date(detail.data.value.published_at).toLocaleString() : 'Not supplied' }}</dd><dt>First discovered</dt><dd>{{ new Date(detail.data.value.first_discovered_at).toLocaleString() }}</dd></dl><article v-for="source in detail.data.value.provenance" :key="source.feed_id" class="provenance"><strong>{{ source.feed_name }}</strong><p>{{ source.description || 'No RSS description.' }}</p></article></template></section></div>
</template>
